[package]
name = "parallel"
version = "0.1.0"
authors = ["skyne"]

[lib]
name = "parallel"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.41"
rayon = "1.0.1"
cgmath = "0.16.1"